### ISSUE TITLE
Add TypeScript definitions

### ISSUE THREAD

**Issue by levibotelho** [logotype/fixparser#1]
For starters, thanks for the fantastic library. I'm currently using it in a TypeScript project and having a TypeScript definition file would go a long way to make it even more useful. I've coded one up for my personal use but could merge it in here if you were interested. Thoughts?

**Comment by logotype** [comment]
Hi, sorry for the late reply. Yes, TS definitions would be nice!

**Comment by rmeshksar** [comment]
Hi, I know this issue is closed. Just wondering if there is any definition file for this library or nor. I could not find any.
Thanks.

**Comment by logotype** [comment]
Hi

I don’t have the type definitions either. @levibotelho could you send a merge request?

Thanks

**Comment by levibotelho** [comment]
I had written some rudimentary definitions for my work back when I originally did the PR in 2016. Not sure if they're still around or if I'll still have permission to share them. On holiday right now but will check when I return.

**Comment by rmeshksar** [comment]
Thanks for both of you. I will try to create it based on the latest code. It is good opportunity for me to learn and contribute. Will update you on the progress.
