### ISSUE TITLE
connect function is mis-specified

### ISSUE THREAD

**Issue by lostless13** [logotype/fixparser#13]
The connect() function in the FIXParser class doesn't work. It does not properly pass the values to the object instance. (src/FIXParser.js).

The issue seems to be the parameters is misspecified. Currently, the parameter is being evaluated to a blank object.

![image](https://user-images.githubusercontent.com/24193723/43345808-1af861e0-91ac-11e8-97af-b4614d75bb89.png)

This:
`connect({ host = 'localhost', port = '9878', sender = 'SENDER', target = 'TARGET', heartbeatIntervalMs = 60000, fixVersion = this.fixVersion } = {}) {`

Probably should be this:
`connect({ host = 'localhost', port = '9878', sender = 'SENDER', target = 'TARGET', heartbeatIntervalMs = 60000, fixVersion = this.fixVersion }) {`

Or better yet support an object passed in with the various options. Options not included are defaulted.

Thanks.

**Comment by jonfreedman** [comment]
As per the readme the code migrated to gitlab: https://gitlab.com/logotype/fixparser

**Comment by logotype** [comment]
Hey Jon, can you send me an email? I don’t have your email address. Cheers

**Comment by jonfreedman** [comment]
Sure, I'm now mailto:jon.freedman@zoho.com (personal) and mailto:jon.freedman@uk.mlp.com (moved to Millennium a year ago)


---- On Thu, 15 Aug 2019 09:23:18 +0000 Victor Norgren <notifications@github.com> wrote ----


Hey Jon, can you send me an email? I don’t have your email address. Cheers
