### ISSUE TITLE
FIX API is not able to connect 

### ISSUE THREAD

**Issue by jagdishox1991** [logotype/fixparser#15]
Hello,
Using Fixparser,I want to implement FIX API.
I was trying to connect with "Logon". Its sending message but no any response. How can i sure that response comes or not ?
Can you please help to resolve this ?

**Comment by jonfreedman** [comment]
As per the readme the code migrated to gitlab: https://gitlab.com/logotype/fixparser

**Comment by jagdishox1991** [comment]
Thanks for the reply
I want to know how it can be called as i am not getting either Error or Response.

**Comment by jonfreedman** [comment]
Please raise an issue on gitlab

**Comment by jagdishox1991** [comment]
Raised an issue on gitlab. Please check : [https://gitlab.com/logotype/fixparser/issues/26](https://gitlab.com/logotype/fixparser/issues/26)
