### ISSUE TITLE
BeginString field is hardcoded  to FIX.4.2 within Message.encode method. 

### ISSUE THREAD

**Issue by digrich** [logotype/fixparser#7]
How can I send messages for FIX.4.3 version? 

My server understands FIX.4.3 and trying to use fixparser for the client, but fixparser layer is always populating BeginString field to FIX.4.2.

**Comment by jonfreedman** [comment]
Have you tried including `new Field(Fields.BeginString, 'FIX.4.3')` in your call to `fixParser.createMessage`?

**Comment by logotype** [comment]
Hi
fixparser@2.3.5 is now published. You can now override the standard fields (BeginString, BodyLength and CheckSum) like so:

```javascript
import FIXParser, { Field, Fields } from 'fixarser';
const fixParser = new FIXParser();
const message = fixParser.createMessage(
    new Field(BeginString, 'FIX.4.3'),
    new Field(CheckSum, 1234),
    // ...
);
```

**Comment by digrich** [comment]
@jonfreedman I tried that and it failed the parsing.

Thanks, @logotype. I will take the latest code.

**Comment by digrich** [comment]
@logotype Something seems to have broken since fixparser@2.3.5 release. None of the FIX messages are reaching to the server and also no error.  fixParser@2.3.4 is working fine.

**Comment by logotype** [comment]
@digrich just published fixparser@2.3.7. Please check if it works now. Thanks!

**Comment by digrich** [comment]
Thanks, @logotype. It's working now. 

Really appreciate your quick fix and response.

**Comment by digrich** [comment]
@logotype After this change, I can override BeginString for FIX messages but Heartbeat messages are still using internal hardcoded BeignString. 

Right now, all heartbeats are being rejected by the server and I am trying to send heartbeat externally. 

We may need a way to pass fix version either at the time of FIXParser initialization or as a parameter in connect method.

**Comment by logotype** [comment]
@digrich fixparser@2.3.9 published. Thanks a lot for the help and please let me know if any more suggestions or ideas!

**Comment by digrich** [comment]
Thanks, @logotype. It looks fine now.

**Comment by jagdishox1991** [comment]
Hello @logotype 
Thanks for the plugin. 
I want to implement FIX API.
I was trying to connect with "Logon". Its sending message but no any response. How can i sure that response comes or not ?
Can you please help to resolve this ?
